Bugfixes, Statusausgabe, Argparse
hallowed/jugendwort-spammer pull request #13
Opened 2020-07-06 20:56 UTC by 0x0verflow

Hallo, meine Kerle!
Nachdem der HusoBot von Twitter ermordet wurde, musste ich mir ein neues Hobby suchen. Und da wäre ich!
Hier wäre mein Beitrag zu einer besseren Welt:

## Argparse:
- ``-threads`` (Anzahl der Threads bestimmen)
- ``-url`` (URL ändern)
- ``-proxylist``(Proxylist aus Datei laden)
- Manifestierung der Beiträger

## Statusausgabe:
- Status wird jetzt alle 5s **lesbar** ausgegeben
- Bessere Performance (Ich bin Geschwindigkeit!)

## Bugfixes:
- Nichtverwendung des Proxys beim get(...)-Requests am Anfang der vote_thread-Methode. BKA lässt grüßen!
- Umbenennung von main(...) in vote_thread(...). Lesbarkeit und so...

Ich hoffe, dass ich weiterhelfen konnte und ihr den PR annehmt. Ansonsten habe ich jetzt wohl meinen eigenen Fork ¯\_(ツ)_/¯

2020-07-06 22:40 UTC, hallowed commented
Klar wird der angenommen! Fehlt nur noch, ganz gemäß der deutschen Korrektheit, die bessere Ausstattung mit Kommentaren... Außerdem könntest du noch ein weiteres Kommandozeilenargument hinzufügen, mit dem man das Wort bestimmen kann, welches gespammt wird. Natürlich mit einem sehr großen Schriftzug, was Hurensohn doch für ein schönes Wort ist... Aber dennoch wollen einige (nachdem Langenscheidt verkündet hat, dass sie Hurensohn nicht in die Top 10 aufnehmen werden) andere Wörter spammen.

2020-07-07 08:36 UTC, 0x0verflow commented
So, damit wäre der ganze Spaß erledigt. Du kannst jetzt mergen.

2020-07-07 09:38 UTC, ghost requested changes
Obwohl ich auch ein Befürworter der Deutschen Sprache bin, würde ich die Kodierungs-Kommentare weiterhin angelsächsisch halten.

2020-07-07 09:45 UTC, ghost requested changes

2020-07-07 09:45 UTC, darkhunter161 commented on main.py
> +        # Erster Request um Kekse und einen Validierungs-String zu holen
```suggestion
        # first make request to get validation string (csrf) and cookies
```

2020-07-07 09:45 UTC, darkhunter161 commented on main.py
> +        # Den Schlüsselwert parsieren
```suggestion
        # parse the token
```

2020-07-07 09:45 UTC, darkhunter161 commented on main.py
> +        # Eine zufällige Nummer für die Grenznummer generieren
```suggestion
        # generate random boundary number (necessary for the valid form data)
```

2020-07-07 09:45 UTC, darkhunter161 commented on main.py
> +        # Ein Zufälliges alter generieren
```suggestion
        # generate random age (1: 10-15; 2: 16-20; ...)
```

2020-07-07 09:45 UTC, darkhunter161 commented on main.py
> +        # Überprüfen, ob die Anfrage erfolgreich war
```suggestion
        # if this string is in the reponse, the request was successful
```

2020-07-07 18:09 UTC, hallowed commented
Jop. Die Kommentare sollten angelsächsisch sein. Die Informationsschreiben gerne auf Deutsch. Im Quellcode dann eine angelsächsische Beschreibung, was da ausgegeben wird, zu finden sein.

2020-07-08 13:00 UTC, 0x0verflow commented
Wäre erledigt. Noch andere Einwände?

2020-07-08 15:42 UTC, hallowed commented
Wundervoll! Wird gemerged:)

2020-07-08 15:43 UTC, merged

2020-07-08 20:09 UTC, 0x0verflow commented
Problem: der info_msg_thread darf **nicht** in der ``enumerate()`` Methode ignoriert werden, da das Programm sonst nicht wartet, bis er zum letzten Mal durchgelaufen ist. Ist keine große Sache, ist nur ärgerlich. Und - wenn das eh gefixt wird - bitte auch die ``proxie``-typo oben fixen.

2020-07-08 21:55 UTC, hallowed commented
Den Typo fix ich gerne. Aber verstehe nicht, was du mit dem info_msg_thread-Problem meinst. Unten, wenn es darum geht, zu warten, bis die Threads geschlossen sind, wir ja kein Thread ignoriert (außer der Mainthread). Nur oben wird ein Thread mehr gestartet, was nichts am warten auf die Schließung ändert. Kann aber auch sein, dass ich gerade nicht richtig denke, ist ja auch schon spät...

2020-07-10 14:50 UTC, 0x0verflow commented
Macht im Endeffekt keinen Unterschied, wäre nur schöner. Der info_msg_thread wird über einen boolean gestoppt - läuft also nicht von alleine aus. Sobald der bool true ist, kann der Thread auslaufen. Also müssen alle nicht-Haupt-Threads gleich behandelt werden, somit wird **nur** der Main-Thread abgezogen.